### ISSUE TITLE
Calculation of D1, D2 and D3

### ISSUE THREAD

**Issue by U7828217** [fediskhakov/MathCourse#4]
The value of det A=19, D1=19, D2=-38 and D3=38. Therefore, x=19/19=1, y=-38/19=-2 and z=38/19=2.
![Cramer's rule](https://github.com/fediskhakov/MathCourse/assets/168043034/35481eb1-7b1d-43a0-b1f3-68bb5e66a6fc)

**Comment by fediskhakov** [comment]
Good catch, corrected.
